# Generated by Django 4.0.4 on 2022-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid2text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
